#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RcMobileApp.Resource", IsApplication=true)]

namespace RcMobileApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RcMobile.Android.Library.Resource.String.ApplicationName = global::RcMobileApp.Resource.String.ApplicationName;
			global::RcMobile.Android.Library.Resource.String.Hello = global::RcMobileApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int black = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int blue_opt05 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int white_opt05 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int white_opt15 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int white_opt25 = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ApplicationLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int car_icon2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int caricon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_replay = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int item_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int MyButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int MyTextBox = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int refresh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int refresh_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tab_element = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080031
			public const int action_refresh = 2131230769;
			
			// aapt resource value: 0x7f080011
			public const int clientid_msg = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int imageView1 = 2131230735;
			
			// aapt resource value: 0x7f080003
			public const int lblAddress = 2131230723;
			
			// aapt resource value: 0x7f08001a
			public const int lblArrivedDate = 2131230746;
			
			// aapt resource value: 0x7f080005
			public const int lblCity = 2131230725;
			
			// aapt resource value: 0x7f080029
			public const int lblClaimNumber = 2131230761;
			
			// aapt resource value: 0x7f08002e
			public const int lblDueDate = 2131230766;
			
			// aapt resource value: 0x7f08000d
			public const int lblEmail = 2131230733;
			
			// aapt resource value: 0x7f08002b
			public const int lblInsuranceCompanyName = 2131230763;
			
			// aapt resource value: 0x7f080030
			public const int lblLicense = 2131230768;
			
			// aapt resource value: 0x7f080001
			public const int lblNameFirst = 2131230721;
			
			// aapt resource value: 0x7f08000b
			public const int lblPhoneHome = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int lblPostalCode = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int lblProvinceState = 2131230727;
			
			// aapt resource value: 0x7f080018
			public const int lblRoNumber = 2131230744;
			
			// aapt resource value: 0x7f080023
			public const int lblVehicleLicense = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int lblVehicleLicenseState = 2131230757;
			
			// aapt resource value: 0x7f08001f
			public const int lblVehicleMake = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int lblVehicleModel = 2131230753;
			
			// aapt resource value: 0x7f080027
			public const int lblVehicleVin = 2131230759;
			
			// aapt resource value: 0x7f08001d
			public const int lblVehicleYear = 2131230749;
			
			// aapt resource value: 0x7f08002d
			public const int linearLayout1 = 2131230765;
			
			// aapt resource value: 0x7f080017
			public const int login_button = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int password_msg = 2131230741;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int relativeLayout2 = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int textView1 = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int txtAddress = 2131230724;
			
			// aapt resource value: 0x7f08001b
			public const int txtArrivedDate = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int txtCity = 2131230726;
			
			// aapt resource value: 0x7f08002a
			public const int txtClaimNumber = 2131230762;
			
			// aapt resource value: 0x7f080012
			public const int txtClientId = 2131230738;
			
			// aapt resource value: 0x7f08002f
			public const int txtDueOut = 2131230767;
			
			// aapt resource value: 0x7f08000e
			public const int txtEmail = 2131230734;
			
			// aapt resource value: 0x7f08002c
			public const int txtInsuranceCompanyName = 2131230764;
			
			// aapt resource value: 0x7f080002
			public const int txtNameFirst = 2131230722;
			
			// aapt resource value: 0x7f080016
			public const int txtPassword = 2131230742;
			
			// aapt resource value: 0x7f08000c
			public const int txtPhoneHome = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int txtPostalCode = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int txtProvinceState = 2131230728;
			
			// aapt resource value: 0x7f080019
			public const int txtRoNumber = 2131230745;
			
			// aapt resource value: 0x7f080014
			public const int txtUserId = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int txtVehicleLicense = 2131230756;
			
			// aapt resource value: 0x7f080026
			public const int txtVehicleLicenseState = 2131230758;
			
			// aapt resource value: 0x7f080020
			public const int txtVehicleMake = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int txtVehicleModel = 2131230754;
			
			// aapt resource value: 0x7f080028
			public const int txtVehicleVin = 2131230760;
			
			// aapt resource value: 0x7f08001e
			public const int txtVehicleYear = 2131230750;
			
			// aapt resource value: 0x7f080013
			public const int user_msg = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddressLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RoDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoInfoLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RoList = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int default_actionbar_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
